version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
  open-pull-requests-limit: 10
  versioning-strategy: lockfile-only
  ignore:
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: ts-node-dev
    versions:
    - 1.1.1
    - 1.1.2
  - dependency-name: eslint-plugin-prettier
    versions:
    - 3.3.1
  - dependency-name: eslint-import-resolver-typescript
    versions:
    - 2.3.0
